version: "3.9"

## Services

services:

  ######## App with PHP-FPM Container ########

  pg-app:
    build:
      context: ./conf/app
      dockerfile: Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
    container_name: pg-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "${APP_PORT}:8000"
      - "${APP_VITE_PORT}:5173"
    depends_on:
      - pg-mariadb
      - pg-redis
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./www:/var/www
      - ./conf/app/php_additional.ini:/usr/local/etc/php/conf.d/additional.ini
      - ./conf/app/.profile:/home/www-data/.profile
      - ./conf/app/bin:/home/www-data/bin
      - ~/.ssh:/home/www-data/.ssh
      - ~/.gitconfig:/home/www-data/.gitconfig
    networks:
      - pg-network


  ######## Nginx Server Container ########

  pg-nginx:
    image: nginx:stable-alpine
    container_name: pg-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - pg-app
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./www:/var/www
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/log:/var/log/nginx
    networks:
      - pg-network


  ######## MariaDB Container ########

  pg-mariadb:
    image: mariadb:10.2.38-bionic
    container_name: pg-mariadb
    restart: always
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - pg-mariadb-data:/var/lib/mysql
      - ./conf/mariadb:/etc/mysql/sql
    networks:
      - pg-network


  ######## phpMyAdmin Container ########

  pg-phpmyadmin:
    image: phpmyadmin
    container_name: pg-phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: pg-mariadb
      UPLOAD_LIMIT: 512M
    networks:
      - pg-network


  ######## Redis Container ########

  pg-redis:
    image: redis:alpine
    container_name: pg-redis
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - pg-redis-data:/data
      - ./conf/redis/log:/log
    command: ["redis-server"]
    restart: always
    networks:
      - pg-network


  ######## MongoDB Container ########

  pg-mongo:
    image: mongo
    container_name: pg-mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - pg-mongo-data:/data/db
      - pg-mongo-configdb:/data/configdb
    command: [--auth]
    networks:
      - pg-network


  ######## MongoDB Express Container ########

  pg-mongo-express:
    image: mongo-express
    container_name: pg-mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@pg-mongo:27017/
    networks:
      - pg-network


  ######## KrakenD Container ########

  pg-krakend:
    image: devopsfaith/krakend
    container_name: pg-krakend
    ports:
      - "${KRAKEND_PORT}:${KRAKEND_PORT}"
    environment:
      KRAKEND_PORT: ${KRAKEND_PORT}
    volumes:
      - ./conf/krakend:/etc/krakend
    networks:
      - pg-network


## Docker Networks

networks:

  pg-network:
    driver: bridge


## Volumes

volumes:

  pg-mariadb-data:
   driver: local

  pg-redis-data:
    driver: local

  pg-mongo-data:
    driver: local

  pg-mongo-configdb:
    driver: local