version: "3.9"

## Services

services:

  ### App (php, nodejs, python) (ports: php-fpm 9000, octane 8000, vite 5173)

  pg-app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: pg-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "${APP_VITE_PORT:-5173}:5173"
    depends_on:
      - pg-mariadb
      - pg-redis
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./www:/var/www
      - ./app/php_additional.ini:/usr/local/etc/php/conf.d/additional.ini
      - ./app/.profile:/home/www-data/.profile
      - ./app/bin:/home/www-data/bin
      - ~/.ssh:/home/www-data/.ssh:ro
      - ~/.gitconfig:/home/www-data/.gitconfig:ro
    networks:
      - pg-network


  ### Nginx (ports: nginx 80)

  pg-nginx:
    image: nginx:stable-alpine
    container_name: pg-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - pg-app
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    networks:
      - pg-network


  ### MariaDB (ports: mysql 3306)

  pg-mariadb:
    image: mariadb:10.11-rc
    container_name: pg-mariadb
    restart: unless-stopped
    tty: true
    environment:
      TZ: ${WORKSPACE_TIMEZONE} 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - pg-mariadb-data:/var/lib/mysql
      - ./mariadb:/etc/mysql/sql
    networks:
      - pg-network


  ### Redis (ports: redis 6379)

  pg-redis:
    image: redis:alpine3.18
    container_name: pg-redis
    restart: unless-stopped
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - pg-redis-data:/data
      - ./redis/log:/log
    command: ["redis-server"]
    networks:
      - pg-network


  ### MongoDB (ports: mongodb 27017)

  pg-mongo:
    image: mongo:7.0.2
    container_name: pg-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - pg-mongo-data:/data/db
      - pg-mongo-configdb:/data/configdb
    command: [--auth]
    networks:
      - pg-network


  ### KrakenD (ports: krakend 8080)

  pg-krakend:
    image: devopsfaith/krakend:2.5
    container_name: pg-krakend
    restart: unless-stopped
    environment:
      KRAKEND_PORT: ${KRAKEND_PORT:-8080}
    volumes:
      - ./krakend:/etc/krakend
    networks:
      - pg-network


  ### Meilisearch (ports: meilisearch 7700)

  pg-meilisearch:
    image: getmeili/meilisearch:v0.26.1
    container_name: pg-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_MASTER_KEY}
    volumes:
      - pg-meilisearch:/meili_data
    networks:
      - pg-network


  ### phpMyAdmin (ports: gui 80)

  pg-phpmyadmin:
    image: phpmyadmin:5.2
    container_name: pg-phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8010}:80"
    environment:
      PMA_HOST: pg-mariadb
      UPLOAD_LIMIT: 512M
    networks:
      - pg-network

  ### MongoDB Express (ports: gui 8081)

  pg-mongo-express:
    image: mongo-express:1.0.0-20-alpine3.18
    container_name: pg-mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT:-8011}:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@pg-mongo:27017/
    networks:
      - pg-network


  ### Mailpit (ports: smtp 1025, gui 8025)

  pg-mailpit:
    image: axllent/mailpit
    container_name: pg-mailpit
    restart: unless-stopped
    volumes:
      - pg-mailpit:/data
    ports:
      - "${MAILPIT_PORT:-8012}:8025"
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - pg-network


## Networks

networks:

  pg-network:
    driver: bridge


## Volumes

volumes:

  pg-mariadb-data:
   driver: local

  pg-redis-data:
    driver: local

  pg-mongo-data:
    driver: local

  pg-mongo-configdb:
    driver: local

  pg-meilisearch:
    driver: local

  pg-mailpit:
    driver: local